# Generated by Django 5.0.6 on 2024-06-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_empleado_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(max_length=60),
        ),
    ]
